### ISSUE TITLE
mock(class) crashes

### ISSUE THREAD

**Issue by ChrisMash** [azubala/OCMockitoSwift#8]
When trying to use `mock(MyNSObjectSubclass.self` in my tests it's crashing when it tries to cast the mock to `MyNSObjectSubclass`. Not sure if I'm doing something wrong or maybe that's never worked? 🤔

**Comment by azubala** [comment]
@ChrisMash is your `MyNSObjectSubclass` type defined in Swift or it's coming from Objective-C?

**Comment by ChrisMash** [comment]
Awesome response time 💪 

It's defined in Swift.... _and_ ObjC... This is all inside a framework and the type is internal in Swift so it's not accessible to ObjC unless we also define its interface in a header.. maybe that's causing some confusion in the mocking...

**Comment by azubala** [comment]
What I learned that `OCMockito` only works when you mock pure ObjC types. When you have case like this:

```objc
@interface Bar
-(void)test;
@end

@implementation Bar
-(void)test {
}
@end
```

and 

```swift
class Foo: Bar {
     func someMethod() {
     }
}
```

then `mock(Foo.self)` will fail since it's now a "Swift altered type", however `mock(Bar.self)` should work even in Swift test files. Same applies if you add extension to `Bar` in Swift. That's sad I know.

**Comment by ChrisMash** [comment]
Yeah you're probably right, we can't have everything we want I guess 😁
